export const browserCoreExamples = [
  "anvika browser status",
  "anvika browser start",
  "anvika browser stop",
  "anvika browser tabs",
  "anvika browser open https://example.com",
  "anvika browser focus abcd1234",
  "anvika browser close abcd1234",
  "anvika browser screenshot",
  "anvika browser screenshot --full-page",
  "anvika browser screenshot --ref 12",
  "anvika browser snapshot",
  "anvika browser snapshot --format aria --limit 200",
  "anvika browser snapshot --efficient",
  "anvika browser snapshot --labels",
];

export const browserActionExamples = [
  "anvika browser navigate https://example.com",
  "anvika browser resize 1280 720",
  "anvika browser click 12 --double",
  'anvika browser type 23 "hello" --submit',
  "anvika browser press Enter",
  "anvika browser hover 44",
  "anvika browser drag 10 11",
  "anvika browser select 9 OptionA OptionB",
  "anvika browser upload /tmp/anvika/uploads/file.pdf",
  'anvika browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "anvika browser dialog --accept",
  'anvika browser wait --text "Done"',
  "anvika browser evaluate --fn '(el) => el.textContent' --ref 7",
  "anvika browser console --level error",
  "anvika browser pdf",
];
